[build]
  publish = "public"
  command = 'hugo --gc --logLevel debug --templateMetrics --templateMetricsHints -b "${URL:-${DEPLOY_PRIME_URL}}" --logFile hugo_log.txt || (echo "----- HUGO LOG (start) -----"; sed -n "1,200p" hugo_log.txt; echo "----- HUGO LOG (end) -----"; exit 1)'

[build.environment]
  HUGO_VERSION = "0.128.2"
  GO_VERSION = "1.22.x"
  NODE_VERSION = "20"
  HUGO_ENABLEGITINFO = "true"
  HUGO_ENV = "production"

[context.production.environment]
  HUGO_ENV = "production"

[context.deploy-preview]
  command = 'hugo --gc --minify -b "${DEPLOY_PRIME_URL}"'

[context.branch-deploy]
  command = 'hugo --gc --minify -b "${DEPLOY_PRIME_URL}"'

[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
  [plugins.inputs]
    debug = true
